
package com.storeii.nciproject.model.deliveries;

/**
 *
 * @author Darren Robert Lowe
 */

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;


@RestController // @Rest means we don't need to include @ResponseBody
@RequestMapping(path="/webstoredb") // This means URL's start with /webstoredb (after Application path)
public class DriverController {
    @Autowired
    // This means to get the bean called repository
    // which is auto-generated by Spring, we will use it to handle the data
    private DriverRepository driverRepository;
    
    

    // Add new
    // Note: try catch wrapping here will break the server
    @PostMapping(path="/addDriver") // Map ONLY POST Requests
    public Driver addDriver (
        @RequestParam String firstName,
        @RequestParam String surname
    ){
      Driver driver = new Driver();
      driver.setFirstName(firstName);
      driver.setSurname(surname);

      driverRepository.save(driver);
      return driver;
    }
    
    
    // find all
    @GetMapping(path="/getDrivers")
    public Iterable<Driver> getDrivers() {
      return driverRepository.findAll();  // This returns a JSON or XML with the users
    }
    
   
}