/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.storeii.nciproject;

/**
 *
 * @author Main
 */

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;


@RestController // @Rest means we don't need to include @ResponseBody
@RequestMapping(path="/webstoredb") // This means URL's start with /webstoredb (after Application path)
public class SupplierController {
    @Autowired
    // This means to get the bean called repository
    // which is auto-generated by Spring, we will use it to handle the data
    private SupplierRepository supplierRepository;
    
    
    
    // CUSTOMER
    // Adding a new Customer
    // Note: try catch wrapping here will break the server
    /*
    @PostMapping(path="/addLocation") // Map ONLY POST Requests
    public Driver addLocation (
        @RequestParam Driver driver)
    {
      Location n = new Location();
      n.setDriver(driver);
      
      locationRepository.save(n);
      return "Saved";
    }
    */
    
    // find all customers
    @GetMapping(path="/getSuppliers")
    public Iterable<Supplier> getSuppliers() {
        return supplierRepository.findAll();  // This returns a JSON or XML with the users
    }
}